sudo: required
language: ruby
addons:
  chrome: stable

before_install: gem install bundler -v 1.16.0.pre.3

script: bundle exec rspec spec

env:
  matrix:
    - RAILS=4.2.10 AA=1.1.0
    - RAILS=5.1.0 AA=1.2.1
    - RAILS=5.2.1 AA=1.3.1
    - RAILS=5.2.1 AA=1.4.0
rvm:
  - 2.3
  - 2.5
