script: bundle exec rspec spec
env:
  matrix:
    - RAILS=4.0.13
    - RAILS=4.1.5
    - RAILS=4.2.6
rvm:
  - 2.1.5
  - 2.2.0
  - 2.3.0
before_install:
  - gem install bundler -v '= 1.9.3'
  - gem update --system
  - gem --version