name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Tests with Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} Active Admin ${{ matrix.activeadmin }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby: '3.3.0'
            rails: '7.1.0'
            activeadmin: '3.2.0'
    env:
      RAILS: ${{ matrix.rails }}
      AA: ${{ matrix.activeadmin }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: |
          gem install bundler -v '< 2'
          bundle install
          bundle exec rspec spec
